app = "dengjibiaoge"   # 稍后在Fly.io创建应用时会生成实际名称，可以先保留

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 5000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [[services.ports]]
    handlers = ["http"]
    port = "80"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[mounts]]
  source = "data_volume"
  destination = "/app/instance"
